#name: C.D
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#
#      - name: Build do projeto
#        run: mvn clean install -DskipTests
#
#      - name: Login no Docker Hub teste
#        run: docker login -u ${{secrets.DOCKERHUB_CREDENTIALS_USR}} -p ${{secrets.DOCKERHUB_CREDENTIALS_PSW}}
#
#      - name: Obter SHA do Commit
#        id: vars
#        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
#
#      - name: Build da imagem Docker com tags C.D e SHA do commit
#        run: |
#          docker build -t geyson12345/appargocd:latest -t geyson12345/appargocd:${{ env.COMMIT_SHA }} .
#
#      - name: Push da imagem Docker com as tags
#        run: |
#          docker push geyson12345/appargocd:latest
#          docker push geyson12345/appargocd:${{ env.COMMIT_SHA }}
#
