permissions:
  contents: write
name: C.I_C.D

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build do projeto
        run: mvn clean install -DskipTests

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_CREDENTIALS_PSW }}" | docker login -u "${{ secrets.DOCKERHUB_CREDENTIALS_USR }}" --password-stdin

      - name: Build Docker image
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          docker build -t geyson12345/appargocd:${{ env.COMMIT_SHA }} .
          docker tag geyson12345/appargocd:${{ env.COMMIT_SHA }} geyson12345/appargocd:latest

      - name: Push Docker image
        run: |
          docker push geyson12345/appargocd:${{ github.sha }}
          docker push geyson12345/appargocd:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"


      - name: Listar arquivos no diretório raiz
        run: |
            ls -al

      - name: Listar arquivos no diretório k8s
        run: |
             ls -al k8s/
          

      - name: Atualizar imagem no kustomize
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          cd k8s
          kustomize edit set image goserver=geyson12345/appargocd:${{ env.COMMIT_SHA }}

      - name: Configurar git para commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker version"

      - name: Commit e Push da alteração
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualização da versão da imagem Docker"
          branch: main
          github_token: ${{ secrets.DOCKER_TOKEN }}
